ci(github-actions): created lint and test pipelines for every pull_request
MapColonies/shared-components-deprecated pull request #36
Opened 2020-08-25 08:27 UTC by syncush

closes #24

2020-08-25 09:53 UTC, alebinson approved these changes

2020-08-25 09:53 UTC, alebinson commented on package.json
> +    "build:all": "yarn build:react-core && yarn build:react",
lerna as a cross packages tool might be considered rather than lerna scoped script (like in publish) 
Up to you.

2020-08-25 09:53 UTC, alebinson commented on package.json
> +    "test:all": "yarn build:all && yarn test:react-core && yarn test:react",
Same, lerna as a cross packages tool might be considered rather than lerna scoped script (like in publish) 
Up to you.

2020-08-27 13:44 UTC, syncush commented
@alebinson, @rannyeli finished soon the composed storybook therefore I am deleting the demo-app, this PR is waiting for @rannyeli to finish his work

2020-08-27 15:24 UTC, CptSchnitz requested changes

2020-08-27 15:24 UTC, CptSchnitz commented on .github/workflows/lint.yml
> +        run: yarn install
`npx lerna bootstrap`

2020-08-27 15:24 UTC, CptSchnitz commented on .github/workflows/test.yml
> +        run: yarn install
unnecessary as yarn test runs lerna bootstrap, maybe just install lerna as global package.

2020-08-27 15:24 UTC, CptSchnitz commented on package.json
> +    "test": "lerna bootstrap && lerna exec yarn test:nowatch",
` "test": "lerna bootstrap && lerna run test:nowatch",`

2020-08-27 15:25 UTC, CptSchnitz commented on .github/workflows/lint.yml
> +        run: yarn install
also same comment as below with install lerna as global.

2020-08-30 07:56 UTC, syncush commented on .github/workflows/lint.yml
> +        run: yarn install
done

2020-08-30 07:56 UTC, syncush commented on package.json
> +    "test": "lerna bootstrap && lerna exec yarn test:nowatch",
done

2020-08-30 07:56 UTC, syncush commented on .github/workflows/test.yml
> +        run: yarn install
done

2020-08-30 07:57 UTC, CptSchnitz approved these changes

2020-09-02 13:19 UTC, merged